name: Next.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create env file
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env.local
        
    - name: Build
      run: npm run build
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    - name: Test
      run: npm run lint
